language: ruby

addons:
  apt:
    packages:
      # https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
      - docker-ce

services:
- docker

# We expect RAILS_ENV to start off unset, then adjust its value as
# necessary.
before_script:
  - unset RAILS_ENV

cache:
  bundler: true
  directories:
    - $HOME/docker

# see https://blog.travis-ci.com/docker-rate-limits
before_install:
  - >
    if [ ! -z "$DOCKERHUB_PASSWORD" ] && [ ! -z "$DOCKERHUB_USERNAME" ]; then
      echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin  ;
    fi

## https://stackoverflow.com/a/41975912
#before_cache:
#  # Save tagged docker images
#  - >
#    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
#
#before_install:
#  # Load cached docker images
#  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

 
# GEM_ALTERNATIVE_NAME only needed for deployment 
jobs:
  include:
  - stage: test
    script:
    - mkdir tmp
    - GEM_ALTERNATIVE_NAME='' bundle exec rake test

    
before_deploy:
  - |
    nvm install --lts \
      && nvm use --lts \
      && npm i -g \
        semantic-release \
        @semantic-release/git \
        @semantic-release/changelog \
        semantic-release-rubygem

deploy:
  - provider: script
    script: ./release.sh
    on:
      branch: master
