language: ruby

addons:
  apt:
    packages:
      # https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
      - docker-ce

services:
- docker

# We expect RAILS_ENV to start off unset, then adjust its value as
# necessary.
before_script:
  - unset RAILS_ENV
 
# GEM_ALTERNATIVE_NAME only needed for deployment 
jobs:
  include:
  - stage: test
    script:
    - mkdir tmp
    - unset GEM_ALTERNATIVE_NAME
    - bundle exec rake test

    
before_deploy:
  - |
    nvm install --lts \
      && nvm use --lts \
      && npm i -g \
        semantic-release \
        @semantic-release/git \
        @semantic-release/changelog \
        semantic-release-rubygem

deploy:
  - provider: script
    script: rake release
    on:
      branch: master
